### ISSUE TITLE
Custom Dark Mode on iOS

### ISSUE THREAD

**Issue by jcbnlsn** [alessiocancian/react-native-actionsheet#1]
Hi. Thank you for continuing this project.

Here is a feature request. I have an app where you can set dark mode independently of the system setting on iOS.
Would it be possible to make a setting to set the color of the native iOS action sheets independently too?

**Comment by alessiocancian** [comment]
Hi, thank you for the request.
I'll check if this is possible.

**Comment by alessiocancian** [comment]
If you update to v2.4.9 you can use `userInterfaceStyle` prop.

Unfortunately it seems to be supported only from ReactNative v0.63 ([see ActionSheetIOS.showActionSheetWithOptions](https://reactnative.dev/docs/actionsheetios#showactionsheetwithoptions))
