### ISSUE TITLE
theme = "ios" not working on android 

### ISSUE THREAD

**Issue by henryteng07** [alessiocancian/react-native-actionsheet#10]
# Bug

It was mentioned that a similar IOS-like UI is available for Android by passing theme="ios" but it doesn't seem to be working for me.

<ActionSheet
        ref={errorRef}
        options={["Retry download", "Cancel"]}
        cancelButtonIndex={1}
        destructiveButtonIndex={0}
        theme="ios"
        onPress={(index) => {}}
/>

Am I doing something wrong?

**Comment by alessiocancian** [comment]
@henryteng07 what was the problem? Old package version?

**Comment by henryteng07** [comment]
Yes @alessiocancian npm update didn't work so reinstalling the package fixed the issue 😆 thanks
