### ISSUE TITLE
passing options with react-native tags(View , Text)  breaking in ios

### ISSUE THREAD

**Issue by pradeepk7053** [alessiocancian/react-native-actionsheet#13]
I am passing options in form of array. I used some text component and styles it working in android but crashing in ios
      
                <ActionSheet
                        ref={o => (this.ActionSheetQuestion = o)}
                        userInterfaceStyle="light"
                        theme="ios"
                        options={[
                          <Text
                            style={Global_css.actionSheet_font}>
                            Delete
                          </Text>,
                          <Text
                            style={Global_css.actionSheet_font}>
                            Edit
                          </Text>,
                        ]}
                        cancelButtonIndex={2}
                        destructiveButtonIndex={0}
                        onPress={id => {
                          console.log(id)
                        }}
                      />

![Screenshot 2021-09-04 at 2 08 01 PM](https://user-images.githubusercontent.com/47030228/132088650-48125f6a-0bcb-4f90-b08e-54e53de43425.png)

**Comment by alessiocancian** [comment]
Are you using `ActionSheet` or `ActionSheetCustom`?

`ActionSheet` only allows strings as options for iOS because it uses the native ActionSheet.

**Comment by pradeepk7053** [comment]
@alessiocancian thanks it's worked
