### ISSUE TITLE
Ref is getting null

### ISSUE THREAD

**Issue by rutvik24** [alessiocancian/react-native-actionsheet#15]
While pressing Button ref value is get null here is some code and it's log` try { console.log('here', refActionSheet); refActionSheet.show(); } catch (e) {}`
log is like `here null` so that actionsheet is not opening it's open only first after installation or clearing app data

**Comment by alessiocancian** [comment]
Sorry for late reply, I need some more code to understand the problem, like how you use the ref and where you call show method

**Comment by rutvik24** [comment]
sorry @alessiocancian  for wrong usage of code i am using functional component and using ref as a class component that's why i am getting ref null error now issue was resolved
i am giving ref like `ref => refActionsheet = ref` but it has to be given like `refActionsheet`

**Comment by theambidextrous** [comment]
> sorry @alessiocancian for wrong usage of code i am using functional component and using ref as a class component that's why i am getting ref null error now issue was resolved i am giving ref like `ref => refActionsheet = ref` but it has to be given like `refActionsheet`

Hi, did you manage to use this with a functional component?

**Comment by rutvik24** [comment]
yes i got it

**Comment by alessiocancian** [comment]
> > sorry @alessiocancian for wrong usage of code i am using functional component and using ref as a class component that's why i am getting ref null error now issue was resolved i am giving ref like `ref => refActionsheet = ref` but it has to be given like `refActionsheet`
> 
> Hi, did you manage to use this with a functional component?

In functional components you need to use the `useRef` hook
