### ISSUE TITLE
 Invariant Violation: requireNativeComponent: "BlurView" was not found in the UIManager iOS

### ISSUE THREAD

**Issue by theambidextrous** [alessiocancian/react-native-actionsheet#17]
#  Invariant Violation: requireNativeComponent: "BlurView" was not found in the UIManager.

```
This error is located at:
    in BlurView (at BlurView.ios.js:14)
    in BlurView (at ActionSheetCustom.js:214)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at ActionSheetCustom.js:198)
    in RCTSafeAreaView (at SafeAreaView.js:51)
```

## Environment info

| Library                                   | Version |
| ----------------------------------------- | ------- |
| @alessiocancian/react-native-actionsheet | ^3.1.1   |
| react-native                              | 0.64.1   |

## Steps To Reproduce
Am simply using the example code only that i'm wrapping in a functional component 
```
<ActionSheet
          ref={sheetRef}
          title={<SheetTitleText>Choose a store</SheetTitleText>}
          options={options}
          styles={styles}
          cancelButtonIndex={0}
          destructiveButtonIndex={4}
          onPress={(index) => {
            /* do something */
          }}
    />
```
I have my options as a list of Jxs components and not plain strings

Describe what you expected to happen:

1.  Load actionsheet the same way android does

Android screenshort below

![image](https://user-images.githubusercontent.com/13588614/150116146-55182b33-8ff1-49e6-a164-b465c5459264.png)

## Reproducible sample code

Example CustomActionSheet code is what i have above

**Comment by alessiocancian** [comment]
Did you run `pod install`?

If you are using expo you need to downgrade to v2.4.11 because it isn't supported in v3 (see #14)

**Comment by theambidextrous** [comment]
Thanks for reply..

I did run pod install within ios folder. infact i removed the pods folder deleted podfile.lock and i ran pod install.. nothing yet

Am not using Expo

**Comment by theambidextrous** [comment]
I had it resolved. I removed the app on simulator, deleted pods folder, ran pod install  and did a fresh install, somehow this solved it.

**Comment by takecover** [comment]
In my case, refreshing pods didn't work. I installed @react-native-community/blur in my app, and it's been resolved.
