### ISSUE TITLE
Native ActionSheet for iOS is not shown with ActionSheetCustom

### ISSUE THREAD

**Issue by sukanyaevon** [alessiocancian/react-native-actionsheet#8]
The native behaviour of iOS action sheet is not shown when using ActionSheetCustom. 
Here is my code sample:-
import { ActionSheetCustom as ActionSheet } from 'react-native-actionsheet';
  const sheetRef = useRef(null);

onPress=()=>{
if (sheetRef.current) {
        sheetRef?.current?.show();
      }
}

const options = [
    'Cancel',
    'Apple',
    <TouchableOpacity style={{ flexDirection: 'row' }}>
      <Text style={{ color: 'yellow' }}>Banana</Text>
      <ThemedIcon name="User" />
    </TouchableOpacity>,
    'Watermelon',
    <Text style={{ color: 'red' }}>Durian</Text>,
  ];

<ActionSheet
        ref={sheetRef}
        title={<Text style={{ color: '#000', fontSize: 18 }}>Which one do you like?</Text>}
        options={options}
        cancelButtonIndex={0}
        destructiveButtonIndex={4}
        onPress={closeActionSheet}
      />

on iOS it still giving the UI as Android.
What have I missed? 
![Simulator Screen Shot - iPhone 8 - 2021-06-23 at 12 24 51](https://user-images.githubusercontent.com/35032724/123071659-7cab8180-d432-11eb-8c98-ff2c1e8261e1.png)

**Comment by arunabhverma** [comment]
yes, same issue

**Comment by alessiocancian** [comment]
This is the expected behavior, native ActionSheet doesn't support custom colors and custom buttons, so the custom gui is used for iOS too.

I can make the GUI look similar to the native one but there's no way to use the native ActionSheet for ActionSheetCustom.

**Comment by arunabhverma** [comment]
But ui is not similar to native, if you can do something...

**Comment by alessiocancian** [comment]
Working on it, still not the same but starting to look similar

<img src="https://user-images.githubusercontent.com/18497523/124103129-4472f700-da61-11eb-8b51-ffef8baf02c7.png" width=400 />

**Comment by alessiocancian** [comment]
UPDATE: almost the same now, I added blurred background too.
Now I need to handle dark mode and some minor fix and then it's ready to publish 😁

<img src="https://user-images.githubusercontent.com/18497523/124109906-ee558200-da67-11eb-92e4-bcf5d6702446.png" width=400 />

**Comment by alessiocancian** [comment]
Released, you can try installing v3.0.1

**Comment by alessiocancian** [comment]
Released, you can try installing v3.0.1

@jeon9878  @arunabhverma

**Comment by arunabhverma** [comment]
Great sir

**Comment by alessiocancian** [comment]
Please update to v3.0.3, I found a bug with scrollviews (#9)

**Comment by arunabhverma** [comment]
![Screenshot 2021-07-02 at 11 08 14 AM](https://user-images.githubusercontent.com/59590144/124225882-cd536680-db25-11eb-9485-568560326afd.png)
getting this error after installing latest package

**Comment by alessiocancian** [comment]
> ![Screenshot 2021-07-02 at 11 08 14 AM](https://user-images.githubusercontent.com/59590144/124225882-cd536680-db25-11eb-9485-568560326afd.png)
> getting this error after installing latest package
> 

You need to run `pod install` from `ios` folder

**Comment by alessiocancian** [comment]
> getting this error after installing latest package
> 

You need to run `pod install` from `ios` folder

**Comment by arunabhverma** [comment]
Giving same error after installing the pods

**Comment by alessiocancian** [comment]
> Giving same error after installing the pods

That's strange...
Did you run `npm run ios` or `react-native run-ios` after installing the pods?

**Comment by alessiocancian** [comment]
> Giving same error after installing the pods

I tested on a new project and I'm having the same issue, looks like the pod is not being found.
I'm looking for a solution... you can try installing `@react-native-community/blur` as a dependency of your project and reinstall pods as workaround.

**Comment by arunabhverma** [comment]
Ok i m try this

**Comment by arunabhverma** [comment]
ya its working but in dark mode 
![image](https://user-images.githubusercontent.com/59590144/124722082-5227f100-df27-11eb-95b2-0c9334e1b8b4.png)
text appearance is bad

**Comment by alessiocancian** [comment]
> ya its working but in dark mode
> ![image](https://user-images.githubusercontent.com/59590144/124722082-5227f100-df27-11eb-95b2-0c9334e1b8b4.png)
> text appearance is bad

Please share your code, more specifically `options` parameter.
If you provide strings as options they should be light blue, if you use `<Text></Text>` or custom views you should set text color yourself.

**Comment by arunabhverma** [comment]
Ok
