### ISSUE TITLE
Scroll not working on v3.x.x

### ISSUE THREAD

**Issue by alessiocancian** [alessiocancian/react-native-actionsheet#9]
# Bug

![simulator_screenshot_551CEC8A-92AA-4C10-B84C-DAE02E8CEA11](https://user-images.githubusercontent.com/18497523/124159588-9df81780-da9b-11eb-9ec2-0352bb97486a.png)

## Environment info

| Library                                   | Version |
| ----------------------------------------- | ------- |
| @alessiocancian/react-native-actionsheet | 3.0.0   |

**Comment by justkd** [comment]
Has this been published to NPM? I'm using 3.0.3 and this issue still persists.

**Comment by alessiocancian** [comment]
> Has this been published to NPM? I'm using 3.0.3 and this issue still persists.

This fix should be in v3.0.3...
Can you send a screenshot? On which os are you experiencing the issue?

**Comment by justkd** [comment]
React Native 0.64.2
@alessiocancian/react-native-actionsheet 3.0.3
iOS for sure. I haven't tried enough different sized Android devices to say if it's the same yet.

It works as expected on some devices (apparently larger), but not on others.

![Untitled (1)](https://user-images.githubusercontent.com/24572031/131709929-8512401e-57cb-4299-822d-e785db99b432.gif)

**Comment by alessiocancian** [comment]
@justKD I think I found the problem, should be fixed in v3.0.4, please test it and let me know 😊

**Comment by justkd** [comment]
@alessiocancian Awesome! I'll be able to check in on it first thing tomorrow.

**Comment by justkd** [comment]
Working for me! Thank you so much for your quick response and fix!
